export const DOCUMENT_DOWNLOAD_FORMATS = {
  ORIGINAL: "Original format",
  BMP: ".bmp",
  CSV: ".csv",
  DOCX: ".docx",
  DOCM: ".docm",
  DOTM: ".dotm",
  DOTX: ".dotx",
  EPUB: ".epub",
  FB2: ".fb2",
  GIF: ".gif",
  HTML: ".html",
  JPG: ".jpg",
  MD: ".md",
  ODP: ".odp",
  ODT: ".odt",
  OTP: ".otp",
  OTT: ".ott",
  PDF: ".pdf",
  PDFA: ".pdfa",
  PNG: ".png",
  POTM: ".potm",
  POTX: ".potx",
  PPSM: ".ppsm",
  PPSX: ".ppsx",
  PPTM: ".pptm",
  RTF: ".rtf",
  TSV: ".tsv",
  TXT: ".txt",
  ODS: ".ods",
  OTS: ".ots",
  XLSM: ".xlsm",
  XLTM: ".xltm",
  XLTX: ".xltx",
} as const;

export const ORIGINAL_DOC_EXTENSIONS: Record<string, string> = {
  Document: ".docx",
  Spreadsheet: ".xlsx",
  Presentation: ".pptx",
  Blank: ".pdf",
};
