name: Sanity Check - Registration Page Availability

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sanity-check:
    name: "Sanity Check - Verify Registration Page Loads"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Sanity Check
        run: npx playwright test tests/registrationPageOpen.spec.js
